Reverts metainfo license to CC0-1.0
lutris/lutris pull request #3293
Opened 2020-11-17 17:40 UTC by A6GibKm

Closes: #3277. 

**cc**: @stephanlachnit  is this Ok?

2020-11-17 20:20 UTC, stephanlachnit requested changes

2020-11-17 20:20 UTC, stephanlachnit commented on debian/copyright
> +License: CC0-1.0
Add to line 14
```
License: CC0-1.0
 On Debian systems, the complete text of the CC0-1.0 license
 can be found in "/usr/share/common-licenses/CC0-1.0".
```

2020-11-17 20:24 UTC, stephanlachnit commented
Btw, the GPL v3 is a perfectly _valid_ license for the metainfo. It just happens that some tools might want to generate a catalog from all apps with metainfo in a certain repository, let's say Flathub or the Debian repository.
It's simply easier to distribute this catalog if every metainfo is licensed under a public domain license, since you don't need to care about copyleft and pedantic attribution.

2020-11-17 21:55 UTC, A6GibKm commented
Then I wonder why the tool made by appstream, intended to enforce their own spec fails on this particular license for metainfo. I asked in places, and the response was: it does not make sense to use a code license for an asset.

2020-11-17 23:31 UTC, stephanlachnit commented
Explaination from the documentation:

> Omitting the license value can result 			in your data not being incorporated into the distribution metadata (so this is a required tag). 		
> A permissive license ensures your data can be combined with arbitrary other data in one file (this means copyleft licenses like the GPL are not suitable as metadata license).

So yeah it's mainly to simplify distribution. Maybe valid is the wrong word here, the metadata might not be shown in a distribution if it's not permissive, thus the warning. At least for KDE Discover, I was able to find it on a local install.

2020-11-17 23:32 UTC, stephanlachnit approved these changes

2020-11-18 04:13 UTC, strycore approved these changes

2020-11-18 04:13 UTC, merged