added [Feature request] Install a runner via the command line #3669
lutris/lutris pull request #3728
Opened 2021-10-10 06:30 UTC by Ahmed-Al-Balochi

Hi Lutris Team, 
I added the features to list, install, and uninstall a runner mentioned in issue #3669.
I hope you find this useful.
Thank you.

2021-10-30 10:32 UTC, AlexanderRavenheart requested changes
In addition to the below mentions, I believe the contents of the new methods you added in lutris/runners/runner.py should actually be in lutris/gui/application.py since these should not be inherited by all the runners, they are just command line handlers for calling the Runner specific methods: is_installed, can_uninstall, install, uninstall, etc.

2021-10-30 10:32 UTC, AlexanderRavenheart commented on lutris/runners/runner.py
>          Runner.name = runner_name
```suggestion
        try:
            runner_class = import_runner(runner_name)
            runner = runner_class()
        except InvalidRunner:
            logger.error("Failed to import Runner: %s", runner_name)
            return
```
InvalidRunner must be included in the import from lutris.runners.

2021-10-30 10:32 UTC, AlexanderRavenheart commented on lutris/runners/runner.py
> +            Runner().uninstall()
```suggestion
            runner.uninstall()
```

2021-10-30 10:39 UTC, AlexanderRavenheart commented on lutris/runners/runner.py
> +        version = version+"-x86_64"
Side note: It appends the arch of the wine version, not a hard-coded suffix. But I checked the list of available versions and all of them are x86_64, so for now appending that suffix is okay, but might need to be reviewed in the future.

2021-10-30 10:46 UTC, AlexanderRavenheart commented on lutris/runners/runner.py
> +        print("Wine Runner is Removed")
Side note: I didn't notice you were using the remove_folder() from lutris/util/system.py. That handles possible errors so nothing else to do here.

2021-11-03 20:20 UTC, Ahmed-Al-Balochi commented
Currently working on migrating the methods from runner.py to application.py.

2021-11-03 21:27 UTC, AlexanderRavenheart approved these changes

2021-11-04 18:00 UTC, Ahmed-Al-Balochi commented
This feature should be done. But please take a look at the ```install_cli ``` and ```install_wine_cli``` because I made changes to those methods.
Thank you.

2021-11-05 22:40 UTC, AlexanderRavenheart commented on lutris/gui/application.py
> +        runner_path = os.path.join(settings.RUNNER_DIR, runner_name)
This should probably be wrapped in try-except, like you did in uninstall_runner_cli bellow.

2021-11-05 22:40 UTC, AlexanderRavenheart approved these changes

2021-11-06 14:01 UTC, Ahmed-Al-Balochi commented
@AlexanderRavenheart,
I have resolved the required changes you asked for plus minor adjustments

2021-11-06 15:14 UTC, AlexanderRavenheart reviewed
Change these 2 and it's all good. 👍🏻

2021-11-06 15:14 UTC, AlexanderRavenheart commented on lutris/gui/application.py
> +            except RunnerInstallationError as ex:
```suggestion
            except (InvalidRunner, RunnerInstallationError) as ex:
```
To cover the possible exception raised by import_runner().

2021-11-06 15:14 UTC, AlexanderRavenheart commented on lutris/gui/application.py
> +            except RunnerInstallationError as ex:
```suggestion
            except (InvalidRunner, RunnerInstallationError) as ex:
```

2021-11-06 15:57 UTC, Ahmed-Al-Balochi commented on lutris/gui/application.py
> +            except RunnerInstallationError as ex:
Done 👍🏻

2021-11-06 16:01 UTC, Ahmed-Al-Balochi commented
Thank you @AlexanderRavenheart for guiding me throughout this process, I have learned a lot. It means a great deal to me that my first ever code contribution was to Lutris which is a daily application for me. It feels great contributing back to this awesome software and its community.
Thanks again, and I look forward to making more contributions :)

2021-11-06 16:04 UTC, AlexanderRavenheart approved these changes

2022-02-02 19:49 UTC, Ahmed-Al-Balochi commented
Hi @AlexanderRavenheart @strycore,
I think this pull request is ready for prime time, can't wait to see it hopefully in the next Lutris release.
Thank you.
Ahmed

2022-02-23 01:09 UTC, strycore commented
Looks good! Merging

2022-02-23 01:09 UTC, merged